//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRigths
    {
        public int Id { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
