// <auto-generated />
namespace Presentation.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitMigration1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitMigration1));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111242292_InitMigration1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
