//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public long Quantity { get; set; }
    
        public virtual Product Products { get; set; }
    }
}
